-- SpazaSure Database Schema Migration
-- Generated from EF Core InitialCreate migration
-- Tables use snake_case naming (UseSnakeCaseNamingConvention)

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS auth_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    event text NOT NULL,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_AuthAuditLogs" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    slug text NOT NULL,
    parent_id uuid,
    icon_url text,
    sort_order smallint NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Categories" PRIMARY KEY (id),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS permissions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    module text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Permissions" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Roles" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY (role_id, permission_id),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    phone text,
    email text,
    password_hash text,
    role_id uuid NOT NULL,
    status text NOT NULL DEFAULT 'active',
    mfa_enabled boolean NOT NULL DEFAULT false,
    mfa_secret text,
    failed_attempts smallint NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Users" PRIMARY KEY (id),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otp_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    phone text,
    email text,
    code text NOT NULL,
    purpose text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY (id),
    CONSTRAINT "FK_OtpCodes_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    device_info text,
    ip_address text,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY (id),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS spaza_shops (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    shop_name text NOT NULL,
    owner_name text NOT NULL,
    owner_id_number text,
    phone text NOT NULL,
    email text,
    address text NOT NULL,
    city text,
    province text,
    postal_code text,
    status text NOT NULL DEFAULT 'pending',
    compliance_status text NOT NULL DEFAULT 'non_compliant',
    onboarding_fee_paid boolean NOT NULL DEFAULT false,
    onboarding_fee_ref text,
    rating_avg numeric(3,2) NOT NULL DEFAULT 0,
    rating_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_SpazaShops" PRIMARY KEY (id),
    CONSTRAINT "FK_SpazaShops_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS suppliers (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    company_name text NOT NULL,
    registration_number text,
    vat_number text,
    contact_person text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    address text,
    city text,
    province text,
    postal_code text,
    tier text NOT NULL DEFAULT 'bronze',
    status text NOT NULL DEFAULT 'pending',
    commission_rate numeric(4,2) NOT NULL DEFAULT 5.00,
    bank_name text,
    bank_account text,
    bank_branch_code text,
    logo_url text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Suppliers" PRIMARY KEY (id),
    CONSTRAINT "FK_Suppliers_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_documents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    shop_id uuid NOT NULL,
    doc_type text NOT NULL,
    doc_url text,
    status text NOT NULL DEFAULT 'pending',
    verified_by uuid,
    verified_at timestamp with time zone,
    expiry_date date,
    rejection_note text,
    guidance_url text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShopDocuments" PRIMARY KEY (id),
    CONSTRAINT "FK_ShopDocuments_SpazaShops_ShopId" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS supplier_documents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    doc_type text NOT NULL,
    doc_url text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    verified_by uuid,
    verified_at timestamp with time zone,
    expiry_date date,
    rejection_note text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_SupplierDocuments" PRIMARY KEY (id),
    CONSTRAINT "FK_SupplierDocuments_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS products (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    category_id uuid,
    name text NOT NULL,
    description text,
    sku text NOT NULL,
    barcode text,
    price numeric(10,2) NOT NULL,
    min_order_qty integer NOT NULL DEFAULT 1,
    stock_qty integer NOT NULL DEFAULT 0,
    unit text NOT NULL DEFAULT 'unit',
    images text NOT NULL DEFAULT '[]',
    is_available boolean NOT NULL DEFAULT true,
    is_approved boolean NOT NULL DEFAULT false,
    approved_by uuid,
    approved_at timestamp with time zone,
    is_food_item boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Products" PRIMARY KEY (id),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_number text NOT NULL,
    shop_id uuid NOT NULL,
    supplier_id uuid NOT NULL,
    group_buy_id uuid,
    status text NOT NULL DEFAULT 'pending',
    delivery_type text NOT NULL DEFAULT 'standard',
    delivery_address text,
    subtotal numeric(10,2) NOT NULL DEFAULT 0,
    delivery_fee numeric(10,2) NOT NULL DEFAULT 0,
    delivery_markup numeric(10,2) NOT NULL DEFAULT 50,
    platform_commission numeric(10,2) NOT NULL DEFAULT 0,
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    rejection_reason text,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Orders" PRIMARY KEY (id),
    CONSTRAINT "FK_Orders_SpazaShops_ShopId" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    discount_pct numeric(5,2) NOT NULL DEFAULT 0,
    line_total numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_OrderItems" PRIMARY KEY (id),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_qr_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    order_item_id uuid,
    qr_code text NOT NULL,
    batch_number text,
    expiry_date date,
    is_scanned boolean NOT NULL DEFAULT false,
    scanned_at timestamp with time zone,
    is_recalled boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ProductQrCodes" PRIMARY KEY (id),
    CONSTRAINT "FK_ProductQrCodes_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS "IX_Categories_ParentId" ON categories(parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Permissions_Name" ON permissions(name);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_Name" ON roles(name);
CREATE INDEX IF NOT EXISTS "IX_Users_RoleId" ON users(role_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Phone" ON users(phone);
CREATE INDEX IF NOT EXISTS "IX_OtpCodes_UserId" ON otp_codes(user_id);
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON refresh_tokens(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SpazaShops_UserId" ON spaza_shops(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Suppliers_UserId" ON suppliers(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Suppliers_RegistrationNumber" ON suppliers(registration_number);
CREATE INDEX IF NOT EXISTS "IX_ShopDocuments_ShopId" ON shop_documents(shop_id);
CREATE INDEX IF NOT EXISTS "IX_SupplierDocuments_SupplierId" ON supplier_documents(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON products(category_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_SupplierId_Sku" ON products(supplier_id, sku);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Orders_OrderNumber" ON orders(order_number);
CREATE INDEX IF NOT EXISTS "IX_Orders_ShopId" ON orders(shop_id);
CREATE INDEX IF NOT EXISTS "IX_Orders_SupplierId" ON orders(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_OrderItems_OrderId" ON order_items(order_id);
CREATE INDEX IF NOT EXISTS "IX_OrderItems_ProductId" ON order_items(product_id);
CREATE INDEX IF NOT EXISTS "IX_ProductQrCodes_ProductId" ON product_qr_codes(product_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductQrCodes_QrCode" ON product_qr_codes(qr_code);

-- Record migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505033156_InitialCreate', '8.0.0')
ON CONFLICT DO NOTHING;

-- Seed roles
INSERT INTO roles (id, name, description, is_active, created_at, updated_at) VALUES
  (gen_random_uuid(), 'supplier', 'Supplier role', true, NOW(), NOW()),
  (gen_random_uuid(), 'spaza_owner', 'Spaza shop owner role', true, NOW(), NOW()),
  (gen_random_uuid(), 'admin', 'Platform admin role', true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Seed a default category
INSERT INTO categories (id, name, slug, sort_order, is_active, created_at, updated_at) VALUES
  (gen_random_uuid(), 'Groceries', 'groceries', 1, true, NOW(), NOW())
ON CONFLICT DO NOTHING;
